force-app/main/default/objects/Udemy_Course__c/Udemy_Course__c.object-meta.xml
<CustomObject>
    <description>Udemy Course</description>
    <label>Udemy Course</label>
    <nameField>
        <label>Udemy Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Udemy Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Udemy_Course__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <label>Coupon Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Udemy_Course__c/fields/Course_URL__c.field-meta.xml
<CustomField>
    <fullName>Course_URL__c</fullName>
    <description>Course URL</description>
    <label>Course URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BitlyInvokationClass.cls
public with sharing class BitlyInvokationClass {

    @InvocableMethod(label='Shorten URL' description='Generate Short URL with Birly API') 
    Public Static Void InvokeBitlyService(List<Id> CourseIds)    {
        System.debug('ID : ' + CourseIds[0]);
        InvokeBitlyServiceFuture(CourseIds);
    }    

    @future(callout=true)
    Public Static Void InvokeBitlyServiceFuture(List<Id> CourseIds)    {
        List<Udemy_Course__c> courseList = [SELECT Id, Name, Course_URL__c, Coupon_Code__c, Short_URL__c FROM Udemy_Course__c 
                                           WHERE Id IN :CourseIds];
        system.debug('Size :' + courseList.size());
        if(courseList.size() > 0)   {
            BitlyIntegrationService bServiceObj = new BitlyIntegrationService();
            for(Udemy_Course__c course : courseList)    {
                if(course.Short_URL__c == NULL || course.Short_URL__c == '')    {
                    String fullURL = course.Course_URL__c;
                    if(course.Coupon_Code__c != NULL)   {
                        fullURL +=  '?couponCode=' + course.Coupon_Code__c;   
                        System.debug('fullURL :' + fullURL);
                    }
                    String shortURL = bServiceObj.GenerateShortenURL(fullURL);
                    system.debug('shortURL : ' + shortURL);
                    course.Short_URL__c = shortURL;       
                }   
            }   
            Update courseList;
        }
    }

}